apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  labels:
    id: "{{ .Values.labels.id }}"
    app: {{ .Values.app.name }}
    env: "{{ .Values.labels.env }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      id: "{{ .Values.labels.id }}"
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        id: "{{ .Values.labels.id }}"
        app: {{ .Values.app.name }}
        env: "{{ .Values.labels.env }}"
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.containerPort }}
{{- if .Values.env }}
          env:
{{- range .Values.env }}
            - name: {{ .name }}
{{- if .value }}
              value: "{{ .value }}"
{{- else if .valueFrom }}
              valueFrom:
{{ .valueFrom | toYaml | indent 16 }}
{{- end }}
{{- end }}
{{- end }}
{{- if .Values.volumeMounts }}
          volumeMounts:
{{ .Values.volumeMounts | toYaml | indent 12 }}
{{- end }}
{{- if .Values.volumes }}
      volumes:
{{ .Values.volumes | toYaml | indent 8 }}
{{- end }}
