apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  labels:
    id: "{{ .Values.labels.id }}"
    app: {{ .Values.app.name }}
    env: "{{ .Values.labels.env }}"
spec:
  selector:
    id: "{{ .Values.labels.id }}"
    app: {{ .Values.app.name }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}