apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mariadb
  namespace: argocd
spec:
  destination:
    namespace: db
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/bunny96-s/wordpress-gitops
    targetRevision: main
    path: mariadb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
