apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-proxy
  namespace: argocd
spec:
  destination:
    namespace: proxy
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/bunny96-s/wordpress-gitops
    targetRevision: main
    path: nginx-proxy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
